class CreateUsers < ActiveRecord::Migration
  def self.up
    create_table "users", :force => true do |t|
    	# auto-generated by RestfulAuthentication
      t.column :login,                     :string
      t.column :email,                     :string
      t.column :crypted_password,          :string, :limit => 40
      t.column :salt,                      :string, :limit => 40
      t.column :created_at,                :datetime
      t.column :updated_at,                :datetime
      t.column :remember_token,            :string
      t.column :remember_token_expires_at, :datetime

	    t.string   "identity_url"	# for open_id login
	    
	    t.string   "avatar_file_name"
	    t.string   "avatar_content_type"
	    t.integer  "avatar_file_size"

			t.column :admin, :boolean, :default => false
    end
    
    # Set default admin user
    User.create :login => 'admin', :email => 'admin@yourcompany.com',
    						:password => 'admin', :password_confirmation => 'admin', :admin => true
  end

  def self.down
    drop_table "users"
  end
end
